# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param sigma variance of the proposal distribution
#' @param x0 the initial value
#' @param N the number of samples
#' @return a randpm sample of Cauchy distribution and the number of candidate points rejected
#' @examples
#' \dontrun{
#' dir_cpp <- 'D:/Rstudio/Rcpp/'
#' source(paste0(dir_cpp,'rwR.R'))
#' sourceCpp(paste0(dir_cpp,'rwC.cpp'))
#' N <- 2000
#' sigma <- .5
#' x0 <- 25
#' rwC <- rwC(sigma, x0, N)
#' print(rwC[N+1]/N)
#' }
#' @export
rwC <- function(sigma, x0, N) {
    .Call('_SC19060_rwC', PACKAGE = 'SC19060', sigma, x0, N)
}

